### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by LapisTomato** [se1exin/ESPBlinds#4]
These are the errors I am getting:

Arduino: 1.8.20 Hourly Build 2021/12/20 07:33 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, dtr (aka nodemcu), 26 MHz, 40MHz, DOUT (compatible), 1MB (FS:64KB OTA:~470KB), 2, nonos-sdk 2.2.1+100 (190703), v2 Lower Memory, Disabled, None, Only Sketch, 115200"
C:\*\*\ESPBlinds-master\ESPBlinds-master\sketch_apr11a\ESPBlinds.ino: In function 'void mqttReconnect()':
ESPBlinds:282:119: error: no matching function for call to 'PubSubClient::connect(const char [18], const char*&, const char*&, const char [30], int, bool, const char [13], bool)'
282 |     if (mqttClient.connect(MQTT_CLIENT_ID, MQTT_USER, MQTT_PASSWORD, MQTT_TOPIC_STATUS, 1, true, "disconnected", false)) {
|                                                                                                                       ^
In file included from C:\*\*\ESPBlinds-master\ESPBlinds-master\sketch_apr11a\ESPBlinds.ino:3:
C:\Users\*\*\Documents\Arduino\libraries\ESP8266_Microgear/PubSubClient.h:119:12: note: candidate: 'virtual boolean PubSubClient::connect(const char*)'
119 |    boolean connect(const char* id);
|            ^~~~~~~
C:\Users\*\*\Documents\Arduino\libraries\ESP8266_Microgear/PubSubClient.h:119:12: note:   candidate expects 1 argument, 8 provided
C:\Users\*\*\Documents\Arduino\libraries\ESP8266_Microgear/PubSubClient.h:120:12: note: candidate: 'virtual boolean PubSubClient::connect(const char*, const char*, const char*)'
120 |    boolean connect(const char* id, const char* user, const char* pass);
|            ^~~~~~~
C:\Users\*\*\Documents\Arduino\libraries\ESP8266_Microgear/PubSubClient.h:120:12: note:   candidate expects 3 arguments, 8 provided
C:\Users\*\*\Documents\Arduino\libraries\ESP8266_Microgear/PubSubClient.h:121:12: note: candidate: 'virtual boolean PubSubClient::connect(const char*, const char*, uint8_t, boolean, const char*)'
121 |    boolean connect(const char* id, const char* willTopic, uint8_t willQos, boolean willRetain, const char* willMessage);
|            ^~~~~~~
C:\Users\*\*\Documents\Arduino\libraries\ESP8266_Microgear/PubSubClient.h:121:12: note:   candidate expects 5 arguments, 8 provided
C:\Users\*\*\Documents\Arduino\libraries\ESP8266_Microgear/PubSubClient.h:122:12: note: candidate: 'virtual boolean PubSubClient::connect(const char*, const char*, const char*, const char*, uint8_t, boolean, const char*)'
122 |    boolean connect(const char* id, const char* user, const char* pass, const char* willTopic, uint8_t willQos, boolean willRetain, const char* willMessage);
|            ^~~~~~~
C:\Users\*\OneDrive\Documents\Arduino\libraries\ESP8266_Microgear/PubSubClient.h:122:12: note:   candidate expects 7 arguments, 8 provided
exit status 1
no matching function for call to 'PubSubClient::connect(const char [18], const char*&, const char*&, const char [30], int, bool, const char [13], bool)'
This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by se1exin** [comment]
@LapisTomato did you install the required Arduino libraries via the Arduino Library Manager?
 - ESP8266WiFi - https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/readme.html
 - PubSubClient - https://www.arduino.cc/reference/en/libraries/pubsubclient/

**Comment by LapisTomato** [comment]
@se1exin Yes I did.

**Comment by se1exin** [comment]
Oh I've missed documented the ESP8266 library, it needs to be installed via Arduino Board Manager.

Here's the first google result I found on how to install it: https://randomnerdtutorials.com/how-to-install-esp8266-board-arduino-ide/

**Comment by LapisTomato** [comment]
@se1exin I already had that installed. Should have sent that picture, sorry.
