### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by apanteleev** [se1exin/ESPBlinds#9]
Hi,
I just wanted to say thanks for publishing these project files. I'm relatively new to the 3D printing and Arduino world, and I used this project to learn how to build a similar device myself, with some improvements. You can find my result at https://github.com/apanteleev/autoblinds and reuse any ideas if you want to.

**Comment by se1exin** [comment]
Hi @apanteleev, thanks for dropping in and saying hi!

I just had a look at your project - I really like the improvements you have made! I might incorporate some of them back into mine if I get some spare time. I especially like that you've added push buttons to control it locally.

Keep up the good work!
